name: Deploy docs
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Deploy via SSH
        uses: JimCronqvist/action-ssh@master
        with:
          host: ${{ secrets.TS_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd nginx_docs
            pipx install mkdocs
            git pull origin main
            mkdocs build
            cd
            sudo cp -r nginx_docs/site/. /var/www/html            
            sudo systemctl restart nginx
